Dwworks additions
IBM/container-service-getting-started-wt pull request #18
Opened 2017-10-03 03:12 UTC by jgarcows

Creating the pull request so automation also has time to run on this.

2017-10-26 14:57 UTC, jgarcows commented on Lab 0/README.md
> +Move the executable file to the `/usr/local/bin` directory with `mv /<path_to_file>/kubectl/usr/local/bin/kubectl` .
Space needed after kubectl on the mv command.  `mv /<path_to_file>/kubectl /usr/local/bin/kubectl`

2017-10-26 16:35 UTC, jgarcows commented on Lab 0/README.md
> +Once the bluemix CLI and the containers-service plugin is installed, you can move on to the next phase of the lab.
This line should be removed, as it is confusing.  Kubectl and bx cr are still needed for Lab 1 (some readers might mistake this as meaning you can leave lab 0 now)

2017-10-31 13:22 UTC, linsun requested changes

2017-10-31 13:22 UTC, linsun commented on Lab 6/README.md
> +# CI/DC with the IBM Bluemix Containers Service
Do you mean CI/CD?

2017-10-31 13:22 UTC, linsun commented on Lab 4/README.md
> +# Federated Kubernetes Cluster: Two Worker Nodes Running the Same Application
does armada support this?

2017-10-31 13:22 UTC, linsun commented on Lab 8/README.md
> +# Before you Begin: Install Istio
The istio portion is v0.1 based, need to be updated for 0.2.

2017-11-03 19:55 UTC, jkomg approved these changes
This LGTM, I'd like to have it added in to start on a clean-ish slate with our edits.

2017-11-10 22:59 UTC, kennjason commented
@jgarcows & @nfritze I'd like to merge this so we can get to work pouring through it, is there any reason not to? We'd rather work from two sources (ours and this) rather than yours + a heavy PR with a ton of content + ours. 

Thoughts?

2017-11-11 20:31 UTC, jgarcows commented
I've been working on doing the merge, hopefully on Monday it will be merged.  Sorry for all the delay.

2017-11-13 13:37 UTC, jgarcows commented
Merged.  I'm closing this pull request.  Please make new pull requests for any changes needed.

2017-11-13 13:37 UTC, closed without merging